name: Release OpenAPI Doc


on:
  workflow_dispatch:
    inputs:
      product:
        description: 'Product'
        required: true
        default: 'ghippo'
        type: choice
        options:
          - mspider
          - ghippo
          - kpanda
      version:
        description: 'Version of api'
        required: true
        type: string
      swagger_json: 
        description: JSON format swagger
        required: true
        type: string
  issues:
    types:
      - opened
      - edited

jobs:
  add-openapi-doc:
    runs-on: ubuntu-latest
    steps: 
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          # label_marker_start: '>>'
          # label_marker_end: '<<'
      - name: Show parsed data JSON
        run: |
          echo "${{ steps.parse.outputs.payload }}"
        
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: OpenAPI PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo ${{ toJson(github.event.issue) }}
          exit 0
          p=${{ github.event.inputs.product }}
          d=docs/zh/docs/openapi/${{ github.event.inputs.product }}
          v=${{ github.event.inputs.version }}
          mkdir -p ${d}
          if [ -f ${d}/${v}.md ]; then
            echo "file already exists"
            exit 1
          fi
          if [ ! -f ${d}/index.md ]; then
            cat > ${d}/index.md <<EOF
          # 全局管理 OpenAPI
          - [版本 ${v}](./${v}.md)
          EOF
          else
            echo "- [版本 ${v}](./${v}.md)" >> ${d}/index.md
          fi
          echo "# <swagger-ui src=${v}.json>" > ${d}/${v}.md
          cat > ${d}/${v}.json <<EOF
          ${{ github.event.inputs.swagger_json }}
          EOF
          git checkout -b feature/add-${p}-${v}-api-doc
          git status
          git add .
          git config user.email "mspider-bot@7jun.cc"
          git config user.name "mspider-bot"
          git commit -m "Add ${p} version ${v} OpenAPI doc"
          git push origin feature/add-${p}-${v}-api-doc 
          gh pr create --title "Add ${p} version ${v} OpenAPI doc" --fill -R kebe7jun/DaoCloud-docs
          gh pr list
